### ISSUE TITLE
run script no longer builds the standard. 

### ISSUE THREAD

**Issue by kohlhase** [OpenMath/OMSTD#66]
I am not totally sure what happens, but `build/trang.txt` gives
```
/Users/kohlhase/vc/git/github.com/OpenMath/OMSTD/build/tmp.rnc:11:45: warning: approximating datatype "anyURI" by "CDATA"
/Users/kohlhase/vc/git/github.com/OpenMath/OMSTD/build/tmp.rnc:25:29: warning: approximating datatype "anyURI" by "CDATA"
Exception in thread "main" java.util.ConcurrentModificationException
	at java.util.Vector$Itr.checkForComodification(Vector.java:1184)
	at java.util.Vector$Itr.next(Vector.java:1137)
	at com.thaiopensource.relaxng.output.dtd.DtdOutput.outputRequiredComponents(Unknown Source)
	at com.thaiopensource.relaxng.output.dtd.DtdOutput.outputParamEntity(Unknown Source)
	at com.thaiopensource.relaxng.output.dtd.DtdOutput.outputRequiredComponents(Unknown Source)
	at com.thaiopensource.relaxng.output.dtd.DtdOutput.outputParamEntity(Unknown Source)
	at com.thaiopensource.relaxng.output.dtd.DtdOutput.outputRequiredComponents(Unknown Source)
	at com.thaiopensource.relaxng.output.dtd.DtdOutput.outputParamEntity(Unknown Source)
	at com.thaiopensource.relaxng.output.dtd.DtdOutput.outputRequiredComponents(Unknown Source)
	at com.thaiopensource.relaxng.output.dtd.DtdOutput.outputElement(Unknown Source)
	at com.thaiopensource.relaxng.output.dtd.DtdOutput$GrammarOutput.visitDefine(Unknown Source)
	at com.thaiopensource.relaxng.output.dtd.DtdOutput$GrammarOutput.visitDefine(Unknown Source)
	at com.thaiopensource.relaxng.edit.DefineComponent.accept(Unknown Source)
	at com.thaiopensource.relaxng.output.dtd.DtdOutput$GrammarOutput.visitContainer(Unknown Source)
	at com.thaiopensource.relaxng.output.dtd.DtdOutput.topLevelOutput(Unknown Source)
	at com.thaiopensource.relaxng.output.dtd.DtdOutput.output(Unknown Source)
	at com.thaiopensource.relaxng.output.dtd.DtdOutputFormat.output(Unknown Source)
	at com.thaiopensource.relaxng.translate.Driver.doMain(Unknown Source)
	at com.thaiopensource.relaxng.translate.Driver.main(Unknown Source)
```
It seems to die silently. 

BTW, I ran `support/install-jars`, so that the trang version should be OK.

**Comment by kohlhase** [comment]
Without this, it is very hard to make progress on the alpha-conversion issue.

**Comment by davidcarlisle** [comment]
works for me locally in master and alpha-conversion branches and it ran on travis three hours ago (or have you fixed this in the meantime?)

**Comment by kohlhase** [comment]
No, still does not run for me. I wonder if that is a MacOS specific thing?

**Comment by davidcarlisle** [comment]
trang is of course rather old I get

$ java -version
java version "1.8.0_131"
Java(TM) SE Runtime Environment (build 1.8.0_131-b11)
Java HotSpot(TM) 64-Bit Server VM (build 25.131-b11, mixed mode)


do you have a newer java, perhaps something broke....

**Comment by davidcarlisle** [comment]
if you just want to progress locally make a copy of the run script and delete all the trang stuff  and pick it up again at 

echo single page html5

you can use the standard *.{dtd,rnc,rng}  from the website which should be good enough (especially as travis will update them if needed)  I don't think I can debug java at a distance (or even locally:-)

**Comment by kohlhase** [comment]
thanks. did that.

**Comment by tkw1536** [comment]
Turns out that Michael had old jars in `/tmp/jars`. The install script does not download new jars if they already exist. Deleting them manually and re-downloading fixed the issue.
